CREATE DATABASE IF NOT EXISTS sekolah;
USE sekolah;

CREATE TABLE IF NOT EXISTS siswa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    kelas VARCHAR(50) NOT NULL
);
